version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - essencial-ja-network

  # Backend API
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=http://localhost:3000,http://localhost:8080,http://localhost:8081
    depends_on:
      - database
    networks:
      - essencial-ja-network

  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=essencial_ja_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - essencial-ja-network

  # Redis (para cache e sessões)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - essencial-ja-network

volumes:
  postgres_data:

networks:
  essencial-ja-network:
    driver: bridge
